import { createSlice } from "@reduxjs/toolkit";

//  Define the initial state for the user slice of the Redux store
const initialState = {
    currentUser: null,  //  Initially no user is signed in
    error: null,    //  Initially no error
    loading: false, //  Initially not loading
}

//  Create a user slice using createSlice function
const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        //  Reducer function to set loading to true when sign-in process starts
        signInStart: (state) => {
            state.loading = true;
        },
        //  Reducer function to update state after successful sign-in
        signInSuccess: (state, action) => {
            state.currentUser = action.payload;
            state.loading = false;
            state.error = null;
        },
        //  Reducer function to update state if sign-in fails
        signInFailure: (state, action) => {
            state.error = action.payload;
            state.loading = false;
        }
    }
});

//  Export action creators generated by createSlice
export const { signInStart, signInSuccess, signInFailure } = userSlice.actions;

//  Export the reducer generated by createSlice
export default userSlice.reducer;